config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "home/about"=>"homes#about", as: 'about'
  
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end
  
  #user
  namespace :user do
    resources :posts, only:[:new,:index,:show,:edit,:create,:destroy,:update]do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
     end
    resources :users, only:[:index,:show,:edit,:update,:destroy]do
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
       get 'followings' => 'relationships#followings', as: 'followings'
       get 'followers' => 'relationships#followers', as: 'followers'
    end
    get "search" => "searches#search"
    resources :messages, only: [:create]
    resources :rooms, only: [:create, :index, :show]
  end
  
  #admin
  namespace :admin do
    resources :users, only:[:show,:edit,:update,:index]
    resources :posts, only:[:index, :new, :show, :create, :destroy]do
      resources :comments, only: [:destroy]
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  #フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :comments
  
  #DM機能
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 80 }

  has_one_attached :image

  #退会処理
  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.guest
     find_or_create_by!(email: 'guest@example.com') do |user|
     user.password = SecureRandom.urlsafe_base64
     user.name = "ゲスト"
    end
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

  #検索機能（完全一致、部分一致、前方一致、後方一致
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path(@user.id), notice: "編集しました"
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :is_deleted, :image, :email)
  end

end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    @comment = Comment.new
  end

  private
  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  
  before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    message = Message.new(message_params)
    message.user_id = current_user.id
    if message.save
      redirect_to user_room_path(message.room)
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "メッセージの送信に失敗しました。"
    end
  end

  private

    def message_params
      params.require(:message).permit(:room_id, :body)
    end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @post = Post.page(params[:page]).per(8)
    @tag_list=Tag.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = current_user.comments.new
    @post_tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
    @post.set_tag
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_posts_path(@post), notice: "投稿しました"
    else
      @posts = Post.all
      render :new
#      redirect_to request.referer
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.touch
    if @post.update(post_params)
      redirect_to user_posts_path, notice: "編集しました"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title,:body,:image,:tag)
  end

end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    room = Room.create
    current_entry = Entry.create(user_id: current_user.id, room_id: room.id)
    another_entry = Entry.create(user_id: params[:entry][:user_id], room_id: room.id)
    redirect_to user_room_path(room)
  end

  def index
    # ログインユーザー所属ルームID取得
    current_entries = current_user.entries
    my_room_id = []
    current_entries.each do |entry|
      my_room_id << entry.room.id
    end
    # 自分のroom_idでuser_idが自分じゃないのを取得
    @another_entries = Entry.where(room_id: my_room_id).where.not(user_id: current_user.id)
  end

  def show
    @room = Room.find(params[:id])
    @messages = @room.messages.all
    @message = Message.new
    @entries = @room.entries
    @another_entry = @entries.where.not(user_id: current_user.id).first
    @user = User.where(id: params[:user_id])
  end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "ユーザー"
      @users = User.looks(params[:search], params[:word])
      render "user/searches/search_result"
    else
      @posts = Post.looks(params[:search], params[:word])
      render "user/searches/search_result"
    end
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.page(params[:page]).per(7)
  end

  def show
    @user = User.find(params[:id])
    @current_entry = Entry.where(user_id: current_user.id)
    @another_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_entry.each do |current|
        @another_entry.each do |another|
          if current.room_id == another.room_id
            @is_room = true
            @room_id = current.room_id
          end
        end
      end
      unless @is_room
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def favorites
    @user = User.find(params[:id])
    favorites= Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end

  def update
   @user = current_user
    if @user.update(user_params)
      redirect_to user_users_path, notice: "編集しました"
    else
      render "edit"
    end
  end
  
  def withdrawal
    @user = User.find(params[:id])
    # ゲストユーザーを退会できないようにする
    if @user.email == 'guest@example.com'
      reset_session
      flash[:notice] = "ゲストユーザーは退会できません"
      redirect_to :root
    else
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
    end
  end
  
  def unsubscribe
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :is_deleted, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
  # 会員の論理削除のための記述。
    def reject_user
      @user = User.find_by(name: params[:user][:name])
      if @user 
        if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
          flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
          redirect_to new_user_registration
        else
          flash[:notice] = "項目を入力してください"
        end
      end
    end
    
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favorites_helper.rb
module User::FavoritesHelper
end

app/helpers/user/messages_helper.rb
module User::MessagesHelper
end

app/helpers/user/posts_helper.rb
module User::PostsHelper
end

app/helpers/user/relationships_helper.rb
module User::RelationshipsHelper
end

app/helpers/user/rooms_helper.rb
module User::RoomsHelper
end

app/helpers/user/searches_helper.rb
module User::SearchesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2 class="mt-5">プロフィールを編集</h2>
      <%= form_with model: @user, url: user_user_path, method: :patch, local:true do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit "保存", class: 'btn btn-secondary' %>
      </div>
    <% end %>
      <div><%= link_to "退会する", user_user_unsubscribe_path(@user), class: "btn btn-danger" %></div>
    </div>
  </div>
</div>

app/views/user/users/favorites.html.erb
<div class="container">
  <div class="col-md-12">
     <h2 class="mt-5">いいね一覧</h2>
        <table class="table table-hover table-inverse">
          <thead>
              <tr>
                <th class="col-3">タイトル</th>
                <th>内容</th>
              </tr>
          </thead>
          <tbody>
            <% @favorite_posts.each do |post|%>
            <tr>
              <td><%= link_to post.title, user_post_path(post.id) %></td>
              <td class="line-break"><%= post.body %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
        
        
        
  </div>
</div>

app/views/user/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>
      <h2 class="mt-5">ユーザー</h2>
  　   <table class='table'>
        <thead>
          <tr>
            <th>プロフ画像</th>
            <th>名前</th>
            <th></th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_image(100, 100) %></td>
              <td><%= user.name %></td>
              <td>フォロー数:<%= user.followings.count %></td>
              <td>フォロワー数:<%= user.followers.count %></td>
              <td><%= render "user/relationships/follow", user: user %></td>
              <td><%= link_to 'Show', user_user_path(user.id), class: "user_#{user.id}" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class=" d-flex mb-3 justify-content-center">
      <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-12'>
      <h2 class="text-center mt-5"><%= @user.name %>さんのぺージ</h2>

      <table class="container table table-borderless">
        <tr class="row">
         <td class="col text-center mt-3">
           <h5 class="font-weight-bold">会員情報</h5>
         </td>
        </tr>
        <tr>
          <td class="col text-center">
           <% if @user == current_user %>
            <%= link_to "編集する", edit_user_user_path(@user), class: "text-dark btn btn-outline-warning btn-sm" %>
           <% end %>
         </td>
         <td>
           <%= link_to "いいね一覧", favorites_user_user_path(@user), class: "text-dark btn btn-outline-danger btn-sm" %>
         </td>
        </tr>
      </table>

      <div class="card mx-auto shadow-lg">
        <table class='table nowrap mt-3'>
          <tbody>
            <tr>
             <td style="width: 10%">image</td>
             <td class="text-center"><%= image_tag @user.get_image(100, 100) %></td>
            </tr>
            <tr>
             <td>name</td>
             <td class="text-center"><%= @user.name %></td>
            </tr>
            <tr>
          	  <td>introduction</td>
          	  <td class="text-center line-break"><%= @user.introduction %></td>
            </tr>
            <tr>
              <td>follows</td>
              <td class="text-center"><%= link_to @user.followings.count, user_user_followings_path(@user) %></td>
            </tr>
            <tr>
              <td>followers</td>
              <td class="text-center"><%= link_to @user.followers.count, user_user_followers_path(@user) %></td>
            </tr>
            <tr>
              <td class="pl-5">
                 <% if current_user != @user %>
                   <%= render "user/relationships/btn", user: @user %>
                 <% end %>
              </td>
              <td class="pr-5">
                <!--ダイレクトメッセージ-->
              <% unless @user.id == current_user.id %>
              <% if @is_room == true %>
               <%= link_to "ダイレクトメッセージ", user_room_path(@room_id,user_id: @user.id) , class: "btn btn-primary"%>
              <% else %>
               <%= form_with model: @room, url: user_rooms_path, local: true do |f|%>
                 <%= fields_for @entry do |r| %>
                   <%= r.hidden_field :user_id, value: @user.id %>
                 <% end %>
                <%= f.submit "チャットを始める" , class: "btn btn-primary" %>
                 <% end %>
                <% end %>
               <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      
   </div>
  </div>
</div>

app/views/user/users/unsubscribe.html.erb
<div class="container">
 <div class="row" >
  <div class="col-md-12">
   <h2 class="mt-5">退会お手続き</h2>
    <p>
      退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
      再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
      本当に退会してよろしいですか？
    </p>
   <%= link_to "退会する", user_user_withdrawal_path, method: :patch, data: { confilm: "本当に退会しますか？" },class: "btn btn-danger" %>
   <%= link_to "退会しない", user_user_path(current_user) , class: "btn btn-primary" %>
  </div>
 </div>
</div>